### ISSUE TITLE
Getting image select values

### ISSUE THREAD

**Issue by leadbellydesign** [reduxframework/redux-framework#113]
I've read through all the other issues here pertaining to the getting option values. So far, I'm getting my CSS option values just fine. However, I'm stumbling with the image select values. 

This is what I'm using (successfully) to return my values for CSS:

``` php
<?php echo theme_options('custom-css'); ?>
```

or

``` css
a, a:visited {
    color:<?php echo theme_options('ppp_link_color', 'regular'); ?>;
    text-decoration:none;
}
```

This is what I'm attempting to use for my image select values:

``` php
<?php if ($ppp['layout_0'] == 1) { ?>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
<?php } ?> 
```

But I've got no joy. Basically, I want to create 6 homepage layout options and when one of the options is chosen, load that WordPress template on the page.

As I recall, I didn't have much luck using the brackets which is why I'm echoing the theme options in the CSS.
