### ISSUE TITLE
Invalid + undocumented CSS output for output/compiler arguments

### ISSUE THREAD

**Issue by Neejoh** [reduxframework/redux-framework#2319]
When I have a simple typography setting which I want to output to CSS using either output or the compiler, some extra stuff is added.
Eg. these two selectors `.wf-loading body,{opacity: 0;}.ie.wf-loading body,{visibility: hidden;}` both have a trailing comma before the opening curly brackets. They should be between selectors, not trailing them.

```php
// [..]
array(
	'id'       		=> 'opt-typography-body',
	'type'     		=> 'typography',
	'title'    		=> __( 'Body font', COMC ),
	'compiler' 		=> array('body'),
	'google'		=> false,
	// [..]
),
// [..]
```
When I set Arial as the font, and 12px as the font-size, this is the generated output:
```css
body{font-family:Arial, sans-serif;line-height:12px;font-weight:normal;font-style:normal;font-size:12px;opacity: 1;visibility: visible;-webkit-transition: opacity 0.24s ease-in-out;-moz-transition: opacity 0.24s ease-in-out;transition: opacity 0.24s ease-in-out;}.wf-loading body,{opacity: 0;}.ie.wf-loading body,{visibility: hidden;}
```
As you can see it has a lot of other stuff in there that makes no sense to me (opacity, visibility, transition, etc). What is it for? It's not documented anywhere, so I would love some info on this subject.
