### ISSUE TITLE
Compiler argument doesn't work with multiple properties and selectors

### ISSUE THREAD

**Issue by rolandrnl** [reduxframework/redux-framework#2638]
Hi,

I'm using Redux 3.5.7.10 and I tried the following:

```php
array(
    'id'            => 'header-height',
    'type'          => 'dimensions',
    'title'         => __( 'Header Height' ),
	'units'   		=> array('px'),
	'width'			=> false,
	'default'  		=> array(
        'height' 	=> '90',
    ),
    'compiler'    => array(
        'height' => '#main-header__outer, header#main-header', 
        'line-height' => '.nav-menu li, .nav-buttons'
    ),
    'required' => array('header-position','=','default'),
),
```

The result is the following:
```css
#main-header__outer,
header#main-header,
.nav-menu li,
.nav-buttons {
    height: 124px;
}
```
I would like line-height for .nav-menu li, and for .nav-buttons. Is it a bug or I forgot something?
